### PR TITLE
Add pipeline to for stories manual deployment

### PR DESCRIPTION
**Pull request by haladamateusz**
How to configure it to work properly on your repo:

Step 1) Go to settings tab in repo view

Click on "Secrets and Variables" then "Actions"

storycoder dev-pipeline-step1

Step 2)  In secrets tab, click new repository secret and add two of them:

storycoder dev-pipeline-step2

```
key: WP_API_USERNAME
value: your username from wordpress (see screen below)
```
wordpress

scroll down and generate application password.
set New Application Password Name to "Github action" and click "Add new application Password"
Copy generate value

image

```
key: WP_API_PASSWORD
value: your application password in parenthesis like "generated application password"
```

Step 3) navigate to variables tab. add two variables:

```
key: STORIES_ROOT 
value: ./stories-dev
```

```
key: WP_URL
value: https://practicecoding.dev or https://storycoder.dev, depends on the environment you want to update
```

image

Step 4) go to Actions tab

image

Step 5) click on "Sync stories" workflow, then "run workflow" and "run workflow" from the dropdown menu

image

After successful run, list of stories should be updated! :)

@thomasstauffer666 I had to comment out your response code checks since they break the pipeline and the whole update process. Without fixing http errors or commenting checks, the pipeline is not able to run.

### CODE REVIEW

**Comment by thomasstauffer666** [comment]
Thanks for your work and also your very long explanation. I belive we should copy this into a markdown somewhere, so it's not lost. I've few questions tough:

Why was it necessary to handle titles differently like e.g.

($ => $.title?.rendered).filter(title => !!title)

was this just an issue with the node version on GitHub?

Do you have any idea from where the 500x errors are or how to fix this? I added this check to avoid the situation like yesterday, when something is not working and not giving a proper output. It would be a bit sad if now this is reverted, because your feedback was correct that it was not good to not show this issues.

**Comment by thomasstauffer666** [comment]
Would it be possible for you to just make a pull-request, with

package.json
and
sync-stories.yaml
and
update.js without the ".filter(title => !!title)"

I'll investigate the issues then by myself (and maybe try to use something else then rendered, if this is not reliable)

**Comment by haladamateusz** [comment]
Changes pushed according to your comment.

When I uncomment "checkResponse" it throws http 500 at
```

Create Media: Resistance_Is_Futile.mp3
post https://practicecoding.dev/wp-json/wp/v2/media

file:///Users/mateuszhalada/WebstormProjects/storycoder.dev-backend/wp.js:23
        throw 'Invalid Response ' + response.statusCode + ' ' + JSON.stringify(body);
        ^
Invalid Response 500 "{\"code\":\"rest_upload_unknown_error\",\"message\":\"File is empty. Please upload something more substantial. This error could also be caused by uploads being disabled in your php.ini file or by post_max_size being defined as smaller than upload_max_filesize in php.ini.\",\"data\":{\"status\":500}}"
(Use `node --trace-uncaught ...` to show where the exception was thrown)

```

**Comment by thomasstauffer666** [comment]
Ok thanks for your information, the 500 error is probably there because your story repo is not updated. There where 2 empty mp3 files, which removed from the story repo.

**Pull request merged**
